// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"testing"

	"github.com/stainless-sdks/nimbleway-cli/internal/mocktest"
	"github.com/stainless-sdks/nimbleway-cli/internal/requestflag"
)

func TestExtract(t *testing.T) {
	t.Skip("Prism tests are disabled")
	mocktest.TestRunMockTestWithFlags(
		t,
		"extract",
		"--debug-options", "{collect_har: true, no_retry_mode: true, record_screen: true, redact: true, show_cursor: true, solve_captcha: true, trace: true, upload_engine_logs: true, verbose: true, with_proxy_usage: true}",
		"--url", "https://example.com/page",
		"--browser", "chrome",
		"--city", "Los Angeles",
		"--client-timeout", "25000",
		"--consent-header=true",
		"--cookies", "[{creation: creation, domain: domain, expires: expires, extensions: [string], hostOnly: true, httpOnly: true, lastAccessed: lastAccessed, maxAge: Infinity, name: name, path: path, pathIsDefault: true, sameSite: strict, secure: true, value: value}]",
		"--country", "US",
		"--device", "desktop",
		"--disable-ip-check=false",
		"--driver", "vx8",
		"--dynamic-parser", "{myParser: bar}",
		"--expected-status-code", "200",
		"--expected-status-code", "201",
		"--export-userbrowser=false",
		"--format", "json",
		"--headers", "{User-Agent: CustomBot/1.0, Accept-Language: en-US}",
		"--http2=true",
		"--ip6=false",
		"--is-xhr=true",
		"--locale", "en-US",
		"--markdown=false",
		"--metadata", "{account_name: acme-corp, definition_id: 456, definition_name: product-scraper, endpoint: /api/v2/scrape, execution_id: exec-abc123, flowit_task_id: task-xyz789, input_id: input-123, pipeline_execution_id: 12345, query_template_id: template-qry-001, source: web-app, template_id: 789, template_name: e-commerce-template}",
		"--method", "GET",
		"--native-mode", "requester",
		"--network-capture", "{method: GET, resource_type: document, status_code: 100, url: {value: value, type: exact}, validation: true, wait_for_requests_count: 0, wait_for_requests_count_timeout: 1}",
		"--no-html=false",
		"--no-userbrowser=false",
		"--os", "windows",
		"--parse=true",
		"--parse-options", "{merge_dynamic: true}",
		"--parser", "{myParser: bar}",
		"--proxy-provider", "brightdata",
		"--proxy-providers", "{brightdata: 70, oxylabs: 30}",
		"--query-template", "{id: 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e, api_type: WEB, pagination: {next_page_params: {foo: bar}}, params: {foo: bar}}",
		"--raw-headers=true",
		"--referrer-type", "random",
		"--render=true",
		"--render-flow", "{wait: bar}",
		"--render-flow", "{click: bar}",
		"--render-options", "{adblock: true, blocked_domains: [ads.example.com, tracker.com], browser_engine: chrome, cache: false, connector_type: webit-cdp, disabled_resources: [image, stylesheet], enable_2captcha: true, extensions: [extension-id-1, extension-id-2], fingerprint_id: fp-abc123, hackium_configuration: {collect_logs: true, do_not_fix_math_salt: true, enable_document_element_spoof: true, enable_document_has_focus: true, enable_fake_navigation_history: true, enable_key_ordering: true, enable_sniffer: true, enable_verbose_logs: true}, headless: true, include_iframes: true, load_local_storage: true, local_storage_keys_to_load: [authToken, userId], mouse_strategy: linear, no_accept_encoding: true, override_permissions: true, random_header_order: true, render_type: load, store_local_storage: true, timeout: 30000, typing_interval: 100, typing_strategy: simple, userbrowser: true, wait_until: networkidle2, with_performance_metrics: true}",
		"--request-timeout", "30000",
		"--return-response-headers-as-header=true",
		"--save-userbrowser=false",
		"--session", "{id: id, prefetch_userbrowser: true, retry: true, timeout: 1}",
		"--skill", "dynamic-content",
		"--skip-ubct=false",
		"--state", "CA",
		"--tag", "campaign-2024-q1",
		"--template", "{name: x, params: {foo: bar}}",
		"--type", "generic",
		"--userbrowser-creation-template-rendered", "{id: id, allowed_parameter_names: [x], render_flow_rendered: [{foo: bar}]}",
	)

	// Check that inner flags have been set up correctly
	requestflag.CheckInnerFlags(extract)

	// Alternative argument passing style using inner flags
	mocktest.TestRunMockTestWithFlags(
		t,
		"extract",
		"--debug-options.collect-har=true",
		"--debug-options.no-retry-mode=true",
		"--debug-options.record-screen=true",
		"--debug-options.redact=true",
		"--debug-options.show-cursor=true",
		"--debug-options.solve-captcha=true",
		"--debug-options.trace=true",
		"--debug-options.upload-engine-logs=true",
		"--debug-options.verbose=true",
		"--debug-options.with-proxy-usage=true",
		"--url", "https://example.com/page",
		"--browser", "chrome",
		"--city", "Los Angeles",
		"--client-timeout", "25000",
		"--consent-header=true",
		"--cookies", "[{creation: creation, domain: domain, expires: expires, extensions: [string], hostOnly: true, httpOnly: true, lastAccessed: lastAccessed, maxAge: Infinity, name: name, path: path, pathIsDefault: true, sameSite: strict, secure: true, value: value}]",
		"--country", "US",
		"--device", "desktop",
		"--disable-ip-check=false",
		"--driver", "vx8",
		"--dynamic-parser", "{myParser: bar}",
		"--expected-status-code", "200",
		"--expected-status-code", "201",
		"--export-userbrowser=false",
		"--format", "json",
		"--headers", "{User-Agent: CustomBot/1.0, Accept-Language: en-US}",
		"--http2=true",
		"--ip6=false",
		"--is-xhr=true",
		"--locale", "en-US",
		"--markdown=false",
		"--metadata.account-name", "acme-corp",
		"--metadata.definition-id", "456",
		"--metadata.definition-name", "product-scraper",
		"--metadata.endpoint", "/api/v2/scrape",
		"--metadata.execution-id", "exec-abc123",
		"--metadata.flowit-task-id", "task-xyz789",
		"--metadata.input-id", "input-123",
		"--metadata.pipeline-execution-id", "12345",
		"--metadata.query-template-id", "template-qry-001",
		"--metadata.source", "web-app",
		"--metadata.template-id", "789",
		"--metadata.template-name", "e-commerce-template",
		"--method", "GET",
		"--native-mode", "requester",
		"--network-capture.method", "GET",
		"--network-capture.resource-type", "document",
		"--network-capture.status-code", "100",
		"--network-capture.url", "{value: value, type: exact}",
		"--network-capture.validation=true",
		"--network-capture.wait-for-requests-count", "0",
		"--network-capture.wait-for-requests-count-timeout", "1",
		"--no-html=false",
		"--no-userbrowser=false",
		"--os", "windows",
		"--parse=true",
		"--parse-options.merge-dynamic=true",
		"--parser", "{myParser: bar}",
		"--proxy-provider", "brightdata",
		"--proxy-providers", "{brightdata: 70, oxylabs: 30}",
		"--query-template.id", "182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e",
		"--query-template.api-type", "WEB",
		"--query-template.pagination", "{next_page_params: {foo: bar}}",
		"--query-template.params", "{foo: bar}",
		"--raw-headers=true",
		"--referrer-type", "random",
		"--render=true",
		"--render-flow", "{wait: bar}",
		"--render-flow", "{click: bar}",
		"--render-options.adblock=true",
		"--render-options.blocked-domains", "[ads.example.com, tracker.com]",
		"--render-options.browser-engine", "chrome",
		"--render-options.cache=false",
		"--render-options.connector-type", "webit-cdp",
		"--render-options.disabled-resources", "[image, stylesheet]",
		"--render-options.enable-2captcha=true",
		"--render-options.extensions", "[extension-id-1, extension-id-2]",
		"--render-options.fingerprint-id", "fp-abc123",
		"--render-options.hackium-configuration", "{collect_logs: true, do_not_fix_math_salt: true, enable_document_element_spoof: true, enable_document_has_focus: true, enable_fake_navigation_history: true, enable_key_ordering: true, enable_sniffer: true, enable_verbose_logs: true}",
		"--render-options.headless=true",
		"--render-options.include-iframes=true",
		"--render-options.load-local-storage=true",
		"--render-options.local-storage-keys-to-load", "[authToken, userId]",
		"--render-options.mouse-strategy", "linear",
		"--render-options.no-accept-encoding=true",
		"--render-options.override-permissions=true",
		"--render-options.random-header-order=true",
		"--render-options.render-type", "load",
		"--render-options.store-local-storage=true",
		"--render-options.timeout", "30000",
		"--render-options.typing-interval", "100",
		"--render-options.typing-strategy", "simple",
		"--render-options.userbrowser=true",
		"--render-options.wait-until", "networkidle2",
		"--render-options.with-performance-metrics=true",
		"--request-timeout", "30000",
		"--return-response-headers-as-header=true",
		"--save-userbrowser=false",
		"--session.id", "id",
		"--session.prefetch-userbrowser=true",
		"--session.retry=true",
		"--session.timeout", "1",
		"--skill", "dynamic-content",
		"--skip-ubct=false",
		"--state", "CA",
		"--tag", "campaign-2024-q1",
		"--template.name", "x",
		"--template.params", "{foo: bar}",
		"--type", "generic",
		"--userbrowser-creation-template-rendered.id", "id",
		"--userbrowser-creation-template-rendered.allowed-parameter-names", "[x]",
		"--userbrowser-creation-template-rendered.render-flow-rendered", "[{foo: bar}]",
	)
}

func TestExtractTemplate(t *testing.T) {
	t.Skip("Prism tests are disabled")
	mocktest.TestRunMockTestWithFlags(
		t,
		"extract-template",
		"--params", "{foo: bar}",
		"--template", "template",
	)
}

func TestMap(t *testing.T) {
	t.Skip("Prism tests are disabled")
	mocktest.TestRunMockTestWithFlags(
		t,
		"map",
		"--url", "https://example.com",
		"--country", "US",
		"--domain-filter", "all",
		"--limit", "1000",
		"--locale", "en-US",
		"--sitemap", "include",
	)
}

func TestSearch(t *testing.T) {
	t.Skip("Prism tests are disabled")
	mocktest.TestRunMockTestWithFlags(
		t,
		"search",
		"--query", "x",
		"--country", "country",
		"--deep-search=true",
		"--end-date", "end_date",
		"--exclude-domain", "string",
		"--include-answer=true",
		"--include-domain", "string",
		"--locale", "locale",
		"--max-subagents", "1",
		"--num-results", "1",
		"--parsing-type", "plain_text",
		"--search-engine", "google_search",
		"--start-date", "start_date",
		"--time-range", "hour",
		"--topic", "general",
	)
}
