#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/Nimbleway/nimble-go,github.com/stainless-sdks/nimbleway-go"

go run ./cmd/nimble "$@"
